include:
  - package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style
    prefer_single_quotes: true
    sort_constructors_first: false  # Disabled to avoid conflicts with Dart style
    avoid_empty_else: true
    unnecessary_late: true