include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - riverpod_lint
  exclude:
    - test_results/**
    - build/**
    - .dart_tool/**
    - docs/**
    - node_modules/**
    - dist/**
    - coverage/**
    - .kotlin/**
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'lib/src/rust/**'
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true
  errors:
    dead_code: warning
    missing_required_param: error
    unused_import: warning
    unused_local_variable: warning
    invalid_annotation_target: ignore
    public_member_api_docs: ignore
    always_use_package_imports: ignore
    lines_longer_than_80_chars: ignore
    avoid_types_on_closure_parameters: ignore
    cascade_invocations: ignore
    always_put_required_named_parameters_first: ignore
    use_setters_to_change_properties: ignore
    specify_nonobvious_property_types: ignore
    avoid_positional_boolean_parameters: ignore
    avoid_slow_async_io: ignore
    unnecessary_lambdas: ignore
    prefer_int_literals: ignore
    no_runtimetype_tostring: ignore
    no_default_cases: ignore
    omit_local_variable_types: ignore
    document_ignores: ignore
    unnecessary_ignore: ignore
    avoid_dynamic_calls: ignore
    unnecessary_breaks: ignore
    unnecessary_raw_strings: ignore
    prefer_foreach: ignore
    one_member_abstracts: ignore
    unnecessary_parenthesis: ignore
    sort_pub_dependencies: ignore
    prefer_const_declarations: ignore
    only_throw_errors: ignore
    flutter_style_todos: ignore

formatter:
  page_width: 100
  trailing_commas: preserve

linter:
  rules:
    # Overrides
    sort_constructors_first: false
    always_use_package_imports: false

    # NOT in VGA
    avoid_multiple_declarations_per_line: true
    directives_ordering: true
    library_prefixes: true
    no_leading_underscores_for_library_prefixes: true
    invalid_case_patterns: true
    null_check_on_nullable_type_parameter: true
    throw_in_finally: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_field_initializers_in_const_classes: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    use_colored_box: true
    use_decorated_box: true
    avoid_redundant_argument_values: true
    avoid_returning_this: true
    collection_methods_unrelated_type: true
    prefer_null_aware_method_calls: true
    package_names: true
    use_super_parameters: true
    unnecessary_to_list_in_spreads: true
    use_enums: true
