// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import '../lib.dart';
import 'models.dart';

// These functions are ignored because they are not marked as `pub`: `detect_encoding_inner`

Future<NormalizedBook> parseFb2({
  required List<int> bytes,
  String? forcedEncoding,
}) => RustLib.instance.api.crateApiApiParseFb2(
  bytes: bytes,
  forcedEncoding: forcedEncoding,
);

Future<NormalizedBook> parseEpub({
  required List<int> bytes,
  String? forcedEncoding,
}) => RustLib.instance.api.crateApiApiParseEpub(
  bytes: bytes,
  forcedEncoding: forcedEncoding,
);

Future<NormalizedBook> parseTxt({
  required List<int> bytes,
  String? forcedEncoding,
}) => RustLib.instance.api.crateApiApiParseTxt(
  bytes: bytes,
  forcedEncoding: forcedEncoding,
);

Future<NormalizedBook> parseDocx({
  required List<int> bytes,
  String? forcedEncoding,
}) => RustLib.instance.api.crateApiApiParseDocx(
  bytes: bytes,
  forcedEncoding: forcedEncoding,
);

Future<NormalizedBook> parseRtf({
  required List<int> bytes,
  String? forcedEncoding,
}) => RustLib.instance.api.crateApiApiParseRtf(
  bytes: bytes,
  forcedEncoding: forcedEncoding,
);

Future<NormalizedBook> parseMobi({
  required List<int> bytes,
  String? forcedEncoding,
}) => RustLib.instance.api.crateApiApiParseMobi(
  bytes: bytes,
  forcedEncoding: forcedEncoding,
);

Future<List<String>> decodeZipEntries({required List<int> bytes}) =>
    RustLib.instance.api.crateApiApiDecodeZipEntries(bytes: bytes);

Future<Uint8List> extractZipEntry({
  required List<int> bytes,
  required String entryName,
}) => RustLib.instance.api.crateApiApiExtractZipEntry(
  bytes: bytes,
  entryName: entryName,
);

Future<String> detectEncoding({required List<int> bytes}) =>
    RustLib.instance.api.crateApiApiDetectEncoding(bytes: bytes);

/// Compute SHA-256 hash of bytes (first `max_bytes` only for efficiency).
Future<String> sha256Hash({required List<int> bytes, BigInt? maxBytes}) =>
    RustLib.instance.api.crateApiApiSha256Hash(
      bytes: bytes,
      maxBytes: maxBytes,
    );

Future<NormalizedBook> parseBook({
  required List<int> bytes,
  required String format,
  String? forcedEncoding,
}) => RustLib.instance.api.crateApiApiParseBook(
  bytes: bytes,
  format: format,
  forcedEncoding: forcedEncoding,
);
