// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import '../lib.dart';
import 'models.dart';

/// Extract blocks from HTML content using html5ever + scraper.
/// Returns a JSON-serialized list of ReaderBlock for Dart consumption.
Future<List<ReaderBlock>> parseHtmlBlocks({required String html}) =>
    RustLib.instance.api.crateApiApiParseHtmlBlocks(html: html);

Future<NormalizedBook> parseFb2({
  required List<int> bytes,
  String? forcedEncoding,
}) => RustLib.instance.api.crateApiApiParseFb2(
  bytes: bytes,
  forcedEncoding: forcedEncoding,
);

Future<NormalizedBook> parseEpub({
  required List<int> bytes,
  String? forcedEncoding,
}) => RustLib.instance.api.crateApiApiParseEpub(
  bytes: bytes,
  forcedEncoding: forcedEncoding,
);

Future<NormalizedBook> parseTxt({
  required List<int> bytes,
  String? forcedEncoding,
}) => RustLib.instance.api.crateApiApiParseTxt(
  bytes: bytes,
  forcedEncoding: forcedEncoding,
);

Future<NormalizedBook> parseDocx({
  required List<int> bytes,
  String? forcedEncoding,
}) => RustLib.instance.api.crateApiApiParseDocx(
  bytes: bytes,
  forcedEncoding: forcedEncoding,
);

Future<NormalizedBook> parseRtf({
  required List<int> bytes,
  String? forcedEncoding,
}) => RustLib.instance.api.crateApiApiParseRtf(
  bytes: bytes,
  forcedEncoding: forcedEncoding,
);

Future<NormalizedBook> parseMobi({
  required List<int> bytes,
  String? forcedEncoding,
}) => RustLib.instance.api.crateApiApiParseMobi(
  bytes: bytes,
  forcedEncoding: forcedEncoding,
);

Future<List<String>> decodeZipEntries({required List<int> bytes}) =>
    RustLib.instance.api.crateApiApiDecodeZipEntries(bytes: bytes);

Future<Uint8List> extractZipEntry({
  required List<int> bytes,
  required String entryName,
}) => RustLib.instance.api.crateApiApiExtractZipEntry(
  bytes: bytes,
  entryName: entryName,
);

Future<String> detectEncoding({required List<int> bytes}) =>
    RustLib.instance.api.crateApiApiDetectEncoding(bytes: bytes);

/// Compute SHA-256 hash of bytes (first `max_bytes` only for efficiency).
Future<String> sha256Hash({required List<int> bytes, BigInt? maxBytes}) =>
    RustLib.instance.api.crateApiApiSha256Hash(
      bytes: bytes,
      maxBytes: maxBytes,
    );

Future<NormalizedBook> parseBook({
  required List<int> bytes,
  required String format,
  String? forcedEncoding,
}) => RustLib.instance.api.crateApiApiParseBook(
  bytes: bytes,
  format: format,
  forcedEncoding: forcedEncoding,
);

/// Extract metadata (title, authors, description) without full chapter parsing.
/// Faster than parse_book when only metadata is needed.
Future<BookMeta> extractMetadata({
  required List<int> bytes,
  required String format,
  String? forcedEncoding,
}) => RustLib.instance.api.crateApiApiExtractMetadata(
  bytes: bytes,
  format: format,
  forcedEncoding: forcedEncoding,
);

/// Extract cover image bytes (if available). Returns empty Vec if no cover.
Future<Uint8List> extractCover({
  required List<int> bytes,
  required String format,
  String? forcedEncoding,
}) => RustLib.instance.api.crateApiApiExtractCover(
  bytes: bytes,
  format: format,
  forcedEncoding: forcedEncoding,
);

/// Stub when pdf feature is disabled.
Future<Uint8List> renderPdfThumbnail({
  required String path,
  required int pageIndex,
  required int width,
}) => RustLib.instance.api.crateApiApiRenderPdfThumbnail(
  path: path,
  pageIndex: pageIndex,
  width: width,
);
