// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import '../lib.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

enum BlockType {
  paragraph,
  heading,
  image,
  quote,
  footnote,
  separator,
  table,
  list,
  epigraph,
  poem,
  cite,
  textAuthor,
  subtitle,
  ;

  Future<void> asStr() => RustLib.instance.api.crateApiModelsBlockTypeAsStr(
    that: this,
  );

  static Future<BlockType> fromStr({required String s}) =>
      RustLib.instance.api.crateApiModelsBlockTypeFromStr(s: s);
}

/// Lightweight book metadata — no chapters, no blocks.
/// Used by extract_metadata() for fast scanning.
class BookMeta {
  final String title;
  final List<String> authors;
  final String? description;

  const BookMeta({
    required this.title,
    required this.authors,
    this.description,
  });

  @override
  int get hashCode => title.hashCode ^ authors.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookMeta &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          authors == other.authors &&
          description == other.description;
}

class NormalizedBook {
  final String id;
  final String title;
  final List<String> authors;
  final String? description;
  final String? coverUrl;
  final List<ReaderChapter> chapters;
  final Value? metadata;

  const NormalizedBook({
    required this.id,
    required this.title,
    required this.authors,
    this.description,
    this.coverUrl,
    required this.chapters,
    this.metadata,
  });

  static Future<NormalizedBook> fromJsonStr({required String json}) =>
      RustLib.instance.api.crateApiModelsNormalizedBookFromJsonStr(json: json);

  Future<String> toJsonString() =>
      RustLib.instance.api.crateApiModelsNormalizedBookToJsonString(
        that: this,
      );

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      authors.hashCode ^
      description.hashCode ^
      coverUrl.hashCode ^
      chapters.hashCode ^
      metadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NormalizedBook &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          authors == other.authors &&
          description == other.description &&
          coverUrl == other.coverUrl &&
          chapters == other.chapters &&
          metadata == other.metadata;
}

class ReaderBlock {
  final int index;
  final String text;
  final BlockType blockType;
  final String? imageUrl;
  final String? noteRef;
  final List<RichSpan>? richSpans;
  final int? headingLevel;
  final bool? ordered;
  final List<ReaderBlock>? listItems;
  final List<List<String>>? tableRows;
  final String? imageAlt;
  final double? textIndent;
  final String? textAlign;
  final String? noteId;

  const ReaderBlock({
    required this.index,
    required this.text,
    required this.blockType,
    this.imageUrl,
    this.noteRef,
    this.richSpans,
    this.headingLevel,
    this.ordered,
    this.listItems,
    this.tableRows,
    this.imageAlt,
    this.textIndent,
    this.textAlign,
    this.noteId,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      text.hashCode ^
      blockType.hashCode ^
      imageUrl.hashCode ^
      noteRef.hashCode ^
      richSpans.hashCode ^
      headingLevel.hashCode ^
      ordered.hashCode ^
      listItems.hashCode ^
      tableRows.hashCode ^
      imageAlt.hashCode ^
      textIndent.hashCode ^
      textAlign.hashCode ^
      noteId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReaderBlock &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          text == other.text &&
          blockType == other.blockType &&
          imageUrl == other.imageUrl &&
          noteRef == other.noteRef &&
          richSpans == other.richSpans &&
          headingLevel == other.headingLevel &&
          ordered == other.ordered &&
          listItems == other.listItems &&
          tableRows == other.tableRows &&
          imageAlt == other.imageAlt &&
          textIndent == other.textIndent &&
          textAlign == other.textAlign &&
          noteId == other.noteId;
}

class ReaderChapter {
  final int index;
  final String title;
  final List<ReaderBlock> blocks;

  const ReaderChapter({
    required this.index,
    required this.title,
    required this.blocks,
  });

  @override
  int get hashCode => index.hashCode ^ title.hashCode ^ blocks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReaderChapter &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          title == other.title &&
          blocks == other.blocks;
}

class RichSpan {
  final String text;
  final bool bold;
  final bool italic;
  final bool superscript;
  final String? href;
  final bool lineBreak;

  const RichSpan({
    required this.text,
    required this.bold,
    required this.italic,
    required this.superscript,
    this.href,
    required this.lineBreak,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      bold.hashCode ^
      italic.hashCode ^
      superscript.hashCode ^
      href.hashCode ^
      lineBreak.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RichSpan &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          bold == other.bold &&
          italic == other.italic &&
          superscript == other.superscript &&
          href == other.href &&
          lineBreak == other.lineBreak;
}
