// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import '../lib.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BookCacheManifest`, `CoreError`, `SearchMatch`, `TextNormalizationMode`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

enum BlockType {
  paragraph,
  heading,
  image,
  quote,
  footnote,
  separator,
  table,
  list,
  epigraph,
  poem,
  cite,
  textAuthor,
  subtitle,
  ;

  Future<void> asStr() => RustLib.instance.api.crateApiModelsBlockTypeAsStr(
    that: this,
  );

  static Future<BlockType> fromStr({required String s}) =>
      RustLib.instance.api.crateApiModelsBlockTypeFromStr(s: s);
}

/// Book format detected by extension or content sniffing.
enum BookFormat {
  fb2,
  epub,
  txt,
  docx,
  rtf,
  mobi,
  azw3,
  prc,
  pdf,
  djvu,
  unknown,
  ;

  Future<void> asStr() => RustLib.instance.api.crateApiModelsBookFormatAsStr(
    that: this,
  );

  Future<FormatCapabilities> capabilities() =>
      RustLib.instance.api.crateApiModelsBookFormatCapabilities(
        that: this,
      );

  static Future<void> extensions() => RustLib.instance.api.crateApiModelsBookFormatExtensions();

  static Future<BookFormat> fromExt({required String ext}) =>
      RustLib.instance.api.crateApiModelsBookFormatFromExt(ext: ext);
}

/// Lightweight book metadata — no chapters, no blocks.
/// Used by extract_metadata() for fast scanning.
class BookMeta {
  final String title;
  final List<String> authors;
  final String? description;
  final String? language;
  final List<String> genres;
  final Uint8List? coverData;
  final List<TocEntry> toc;

  const BookMeta({
    required this.title,
    required this.authors,
    this.description,
    this.language,
    required this.genres,
    this.coverData,
    required this.toc,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      authors.hashCode ^
      description.hashCode ^
      language.hashCode ^
      genres.hashCode ^
      coverData.hashCode ^
      toc.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookMeta &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          authors == other.authors &&
          description == other.description &&
          language == other.language &&
          genres == other.genres &&
          coverData == other.coverData &&
          toc == other.toc;
}

class ChapterLanguage {
  final String lang;
  final double confidence;

  const ChapterLanguage({
    required this.lang,
    required this.confidence,
  });

  @override
  int get hashCode => lang.hashCode ^ confidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterLanguage &&
          runtimeType == other.runtimeType &&
          lang == other.lang &&
          confidence == other.confidence;
}

/// An embedded image extracted from the book.
class EmbeddedImage {
  /// Identifier (filename or URL reference).
  final String id;

  /// MIME type (e.g. "image/jpeg").
  final String mediaType;

  /// Raw image bytes.
  final Uint8List data;

  const EmbeddedImage({
    required this.id,
    required this.mediaType,
    required this.data,
  });

  @override
  int get hashCode => id.hashCode ^ mediaType.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmbeddedImage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          mediaType == other.mediaType &&
          data == other.data;
}

/// Capabilities that each format supports.
class FormatCapabilities {
  final bool metadata;
  final bool cover;
  final bool toc;
  final bool text;
  final bool images;
  final bool css;
  final bool footnotes;

  const FormatCapabilities({
    required this.metadata,
    required this.cover,
    required this.toc,
    required this.text,
    required this.images,
    required this.css,
    required this.footnotes,
  });

  @override
  int get hashCode =>
      metadata.hashCode ^
      cover.hashCode ^
      toc.hashCode ^
      text.hashCode ^
      images.hashCode ^
      css.hashCode ^
      footnotes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FormatCapabilities &&
          runtimeType == other.runtimeType &&
          metadata == other.metadata &&
          cover == other.cover &&
          toc == other.toc &&
          text == other.text &&
          images == other.images &&
          css == other.css &&
          footnotes == other.footnotes;
}

class NormalizedBook {
  final String id;
  final String title;
  final List<String> authors;
  final String? description;
  final String? coverUrl;
  final List<ReaderChapter> chapters;
  final Value? metadata;

  /// New fields
  final BookFormat bookFormat;
  final String? language;
  final List<ParseWarning> warnings;
  final List<EmbeddedImage> images;
  final List<TocEntry> toc;

  const NormalizedBook({
    required this.id,
    required this.title,
    required this.authors,
    this.description,
    this.coverUrl,
    required this.chapters,
    this.metadata,
    required this.bookFormat,
    this.language,
    required this.warnings,
    required this.images,
    required this.toc,
  });

  static Future<NormalizedBook> fromJsonStr({required String json}) =>
      RustLib.instance.api.crateApiModelsNormalizedBookFromJsonStr(json: json);

  Future<String> toJsonString() => RustLib.instance.api.crateApiModelsNormalizedBookToJsonString(
    that: this,
  );

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      authors.hashCode ^
      description.hashCode ^
      coverUrl.hashCode ^
      chapters.hashCode ^
      metadata.hashCode ^
      bookFormat.hashCode ^
      language.hashCode ^
      warnings.hashCode ^
      images.hashCode ^
      toc.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NormalizedBook &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          authors == other.authors &&
          description == other.description &&
          coverUrl == other.coverUrl &&
          chapters == other.chapters &&
          metadata == other.metadata &&
          bookFormat == other.bookFormat &&
          language == other.language &&
          warnings == other.warnings &&
          images == other.images &&
          toc == other.toc;
}

/// Non-fatal warning from parsing.
class ParseWarning {
  final String message;

  const ParseWarning({
    required this.message,
  });

  @override
  int get hashCode => message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParseWarning && runtimeType == other.runtimeType && message == other.message;
}

class ReaderBlock {
  final int index;
  final String text;
  final BlockType blockType;
  final String? imageUrl;
  final String? noteRef;
  final List<RichSpan>? richSpans;
  final int? headingLevel;
  final bool? ordered;
  final List<ReaderBlock>? listItems;
  final List<List<String>>? tableRows;
  final String? imageAlt;
  final double? textIndent;
  final String? textAlign;
  final String? noteId;

  const ReaderBlock({
    required this.index,
    required this.text,
    required this.blockType,
    this.imageUrl,
    this.noteRef,
    this.richSpans,
    this.headingLevel,
    this.ordered,
    this.listItems,
    this.tableRows,
    this.imageAlt,
    this.textIndent,
    this.textAlign,
    this.noteId,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      text.hashCode ^
      blockType.hashCode ^
      imageUrl.hashCode ^
      noteRef.hashCode ^
      richSpans.hashCode ^
      headingLevel.hashCode ^
      ordered.hashCode ^
      listItems.hashCode ^
      tableRows.hashCode ^
      imageAlt.hashCode ^
      textIndent.hashCode ^
      textAlign.hashCode ^
      noteId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReaderBlock &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          text == other.text &&
          blockType == other.blockType &&
          imageUrl == other.imageUrl &&
          noteRef == other.noteRef &&
          richSpans == other.richSpans &&
          headingLevel == other.headingLevel &&
          ordered == other.ordered &&
          listItems == other.listItems &&
          tableRows == other.tableRows &&
          imageAlt == other.imageAlt &&
          textIndent == other.textIndent &&
          textAlign == other.textAlign &&
          noteId == other.noteId;
}

class ReaderChapter {
  final int index;
  final String title;
  final List<ReaderBlock> blocks;

  const ReaderChapter({
    required this.index,
    required this.title,
    required this.blocks,
  });

  @override
  int get hashCode => index.hashCode ^ title.hashCode ^ blocks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReaderChapter &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          title == other.title &&
          blocks == other.blocks;
}

class RichSpan {
  final String text;
  final bool bold;
  final bool italic;
  final bool superscript;
  final String? href;
  final bool lineBreak;

  const RichSpan({
    required this.text,
    required this.bold,
    required this.italic,
    required this.superscript,
    this.href,
    required this.lineBreak,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      bold.hashCode ^
      italic.hashCode ^
      superscript.hashCode ^
      href.hashCode ^
      lineBreak.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RichSpan &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          bold == other.bold &&
          italic == other.italic &&
          superscript == other.superscript &&
          href == other.href &&
          lineBreak == other.lineBreak;
}

/// TOC entry for navigation.
class TocEntry {
  final String title;

  /// Chapter index (0-based) or -1 for non-chapter entries.
  final int chapterIndex;

  /// Nested sub-entries.
  final List<TocEntry> children;

  const TocEntry({
    required this.title,
    required this.chapterIndex,
    required this.children,
  });

  @override
  int get hashCode => title.hashCode ^ chapterIndex.hashCode ^ children.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TocEntry &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          chapterIndex == other.chapterIndex &&
          children == other.children;
}
