[package]
name = "glibusta-fuzz"
version = "0.1.0"
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
glibusta_core = { path = ".." }
libfuzzer-sys = "0.4"

[[bin]]
name = "fuzz_fb2"
path = "fuzz_targets/fuzz_fb2.rs"
test = false
doc = false

[[bin]]
name = "fuzz_epub_opf"
path = "fuzz_targets/fuzz_epub_opf.rs"
test = false
doc = false

[[bin]]
name = "fuzz_html_cleaner"
path = "fuzz_targets/fuzz_html_cleaner.rs"
test = false
doc = false

[[bin]]
name = "fuzz_rtf"
path = "fuzz_targets/fuzz_rtf.rs"
test = false
doc = false

[[bin]]
name = "fuzz_mobi_header"
path = "fuzz_targets/fuzz_mobi_header.rs"
test = false
doc = false
