// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'api/api.dart';
import 'api/models.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -942280480;

  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
    stem: 'glibusta_core',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiModelsBlockTypeAsStr({required BlockType that});

  Future<BlockType> crateApiModelsBlockTypeFromStr({required String s});

  Future<void> crateApiModelsBookFormatAsStr({required BookFormat that});

  Future<FormatCapabilities> crateApiModelsBookFormatCapabilities({
    required BookFormat that,
  });

  Future<void> crateApiModelsBookFormatExtensions();

  Future<BookFormat> crateApiModelsBookFormatFromExt({required String ext});

  Future<String> crateApiApiCalculateHash({required String path});

  Future<List<String>> crateApiApiDecodeZipEntries({required List<int> bytes});

  Future<ChapterLanguage> crateApiApiDetectChapterLanguage({
    required String text,
  });

  Future<String> crateApiApiDetectEncoding({required List<int> bytes});

  Future<String> crateApiApiDetectFormat({required String path});

  Future<Uint8List> crateApiApiExtractCover({required String path});

  Future<BookMeta> crateApiApiExtractMetadata({required String path});

  Future<Uint8List> crateApiApiExtractZipEntry({
    required List<int> bytes,
    required String entryName,
  });

  Future<ImportReport> crateApiApiGenerateImportReport({required String path});

  Future<Uint8List> crateApiApiGetAssetBytes({
    required String path,
    required String assetId,
  });

  Future<List<BookAssetMeta>> crateApiApiGetBookAssets({required String path});

  Future<FormatCapabilities> crateApiApiGetFormatCapabilities({
    required String path,
  });

  Future<NormalizedBook> crateApiModelsNormalizedBookFromJsonStr({
    required String json,
  });

  Future<String> crateApiModelsNormalizedBookToJsonString({
    required NormalizedBook that,
  });

  Future<NormalizedBook> crateApiApiParseBook({required String path});

  Future<NormalizedBook> crateApiApiParseBookLegacy({
    required List<int> bytes,
    required String format,
    String? forcedEncoding,
  });

  Future<NormalizedBook> crateApiApiParseBookWithTimeout({
    required String path,
    required BigInt timeoutSecs,
  });

  Future<NormalizedBook> crateApiApiParseDocx({
    required List<int> bytes,
    String? forcedEncoding,
  });

  Future<NormalizedBook> crateApiApiParseEpub({
    required List<int> bytes,
    String? forcedEncoding,
  });

  Future<NormalizedBook> crateApiApiParseFb2({
    required List<int> bytes,
    String? forcedEncoding,
  });

  Future<List<ReaderBlock>> crateApiApiParseHtmlBlocks({required String html});

  Future<NormalizedBook> crateApiApiParseMobi({
    required List<int> bytes,
    String? forcedEncoding,
  });

  Future<NormalizedBook> crateApiApiParseRtf({
    required List<int> bytes,
    String? forcedEncoding,
  });

  Future<List<TocEntry>> crateApiApiParseToc({required String path});

  Future<NormalizedBook> crateApiApiParseTxt({
    required List<int> bytes,
    String? forcedEncoding,
  });

  Future<Uint8List> crateApiApiRenderPdfThumbnail({
    required String path,
    required int pageIndex,
    required int width,
  });

  Future<NormalizedBook> crateApiApiSafeParseBook({required String path});

  Future<String> crateApiApiSha256Hash({
    required List<int> bytes,
    BigInt? maxBytes,
  });

  Future<BookValidationResult> crateApiApiValidateBook({required String path});

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Value;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Value;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ValuePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiModelsBlockTypeAsStr({required BlockType that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_block_type(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelsBlockTypeAsStrConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsBlockTypeAsStrConstMeta => const TaskConstMeta(
    debugName: 'block_type_as_str',
    argNames: ['that'],
  );

  @override
  Future<BlockType> crateApiModelsBlockTypeFromStr({required String s}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(s, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_block_type,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelsBlockTypeFromStrConstMeta,
        argValues: [s],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsBlockTypeFromStrConstMeta => const TaskConstMeta(
    debugName: 'block_type_from_str',
    argNames: ['s'],
  );

  @override
  Future<void> crateApiModelsBookFormatAsStr({required BookFormat that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_book_format(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelsBookFormatAsStrConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsBookFormatAsStrConstMeta => const TaskConstMeta(
    debugName: 'book_format_as_str',
    argNames: ['that'],
  );

  @override
  Future<FormatCapabilities> crateApiModelsBookFormatCapabilities({
    required BookFormat that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_book_format(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_format_capabilities,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelsBookFormatCapabilitiesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsBookFormatCapabilitiesConstMeta => const TaskConstMeta(
    debugName: 'book_format_capabilities',
    argNames: ['that'],
  );

  @override
  Future<void> crateApiModelsBookFormatExtensions() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelsBookFormatExtensionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsBookFormatExtensionsConstMeta => const TaskConstMeta(
    debugName: 'book_format_extensions',
    argNames: [],
  );

  @override
  Future<BookFormat> crateApiModelsBookFormatFromExt({required String ext}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_book_format,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelsBookFormatFromExtConstMeta,
        argValues: [ext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsBookFormatFromExtConstMeta => const TaskConstMeta(
    debugName: 'book_format_from_ext',
    argNames: ['ext'],
  );

  @override
  Future<String> crateApiApiCalculateHash({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiCalculateHashConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiCalculateHashConstMeta => const TaskConstMeta(
    debugName: 'calculate_hash',
    argNames: ['path'],
  );

  @override
  Future<List<String>> crateApiApiDecodeZipEntries({required List<int> bytes}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiDecodeZipEntriesConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiDecodeZipEntriesConstMeta => const TaskConstMeta(
    debugName: 'decode_zip_entries',
    argNames: ['bytes'],
  );

  @override
  Future<ChapterLanguage> crateApiApiDetectChapterLanguage({
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chapter_language,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiDetectChapterLanguageConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiDetectChapterLanguageConstMeta => const TaskConstMeta(
    debugName: 'detect_chapter_language',
    argNames: ['text'],
  );

  @override
  Future<String> crateApiApiDetectEncoding({required List<int> bytes}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiDetectEncodingConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiDetectEncodingConstMeta => const TaskConstMeta(
    debugName: 'detect_encoding',
    argNames: ['bytes'],
  );

  @override
  Future<String> crateApiApiDetectFormat({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiDetectFormatConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiDetectFormatConstMeta => const TaskConstMeta(
    debugName: 'detect_format',
    argNames: ['path'],
  );

  @override
  Future<Uint8List> crateApiApiExtractCover({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiExtractCoverConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiExtractCoverConstMeta => const TaskConstMeta(
    debugName: 'extract_cover',
    argNames: ['path'],
  );

  @override
  Future<BookMeta> crateApiApiExtractMetadata({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_book_meta,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiExtractMetadataConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiExtractMetadataConstMeta => const TaskConstMeta(
    debugName: 'extract_metadata',
    argNames: ['path'],
  );

  @override
  Future<Uint8List> crateApiApiExtractZipEntry({
    required List<int> bytes,
    required String entryName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_String(entryName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiExtractZipEntryConstMeta,
        argValues: [bytes, entryName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiExtractZipEntryConstMeta => const TaskConstMeta(
    debugName: 'extract_zip_entry',
    argNames: ['bytes', 'entryName'],
  );

  @override
  Future<ImportReport> crateApiApiGenerateImportReport({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_import_report,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiGenerateImportReportConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiGenerateImportReportConstMeta => const TaskConstMeta(
    debugName: 'generate_import_report',
    argNames: ['path'],
  );

  @override
  Future<Uint8List> crateApiApiGetAssetBytes({
    required String path,
    required String assetId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(assetId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiGetAssetBytesConstMeta,
        argValues: [path, assetId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiGetAssetBytesConstMeta => const TaskConstMeta(
    debugName: 'get_asset_bytes',
    argNames: ['path', 'assetId'],
  );

  @override
  Future<List<BookAssetMeta>> crateApiApiGetBookAssets({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_book_asset_meta,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiGetBookAssetsConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiGetBookAssetsConstMeta => const TaskConstMeta(
    debugName: 'get_book_assets',
    argNames: ['path'],
  );

  @override
  Future<FormatCapabilities> crateApiApiGetFormatCapabilities({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_format_capabilities,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiGetFormatCapabilitiesConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiGetFormatCapabilitiesConstMeta => const TaskConstMeta(
    debugName: 'get_format_capabilities',
    argNames: ['path'],
  );

  @override
  Future<NormalizedBook> crateApiModelsNormalizedBookFromJsonStr({
    required String json,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_normalized_book,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModelsNormalizedBookFromJsonStrConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsNormalizedBookFromJsonStrConstMeta => const TaskConstMeta(
    debugName: 'normalized_book_from_json_str',
    argNames: ['json'],
  );

  @override
  Future<String> crateApiModelsNormalizedBookToJsonString({
    required NormalizedBook that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_normalized_book(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModelsNormalizedBookToJsonStringConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsNormalizedBookToJsonStringConstMeta => const TaskConstMeta(
    debugName: 'normalized_book_to_json_string',
    argNames: ['that'],
  );

  @override
  Future<NormalizedBook> crateApiApiParseBook({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_normalized_book,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiParseBookConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiParseBookConstMeta => const TaskConstMeta(
    debugName: 'parse_book',
    argNames: ['path'],
  );

  @override
  Future<NormalizedBook> crateApiApiParseBookLegacy({
    required List<int> bytes,
    required String format,
    String? forcedEncoding,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_String(format, serializer);
          sse_encode_opt_String(forcedEncoding, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_normalized_book,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiParseBookLegacyConstMeta,
        argValues: [bytes, format, forcedEncoding],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiParseBookLegacyConstMeta => const TaskConstMeta(
    debugName: 'parse_book_legacy',
    argNames: ['bytes', 'format', 'forcedEncoding'],
  );

  @override
  Future<NormalizedBook> crateApiApiParseBookWithTimeout({
    required String path,
    required BigInt timeoutSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_u_64(timeoutSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_normalized_book,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiParseBookWithTimeoutConstMeta,
        argValues: [path, timeoutSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiParseBookWithTimeoutConstMeta => const TaskConstMeta(
    debugName: 'parse_book_with_timeout',
    argNames: ['path', 'timeoutSecs'],
  );

  @override
  Future<NormalizedBook> crateApiApiParseDocx({
    required List<int> bytes,
    String? forcedEncoding,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_opt_String(forcedEncoding, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_normalized_book,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiParseDocxConstMeta,
        argValues: [bytes, forcedEncoding],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiParseDocxConstMeta => const TaskConstMeta(
    debugName: 'parse_docx',
    argNames: ['bytes', 'forcedEncoding'],
  );

  @override
  Future<NormalizedBook> crateApiApiParseEpub({
    required List<int> bytes,
    String? forcedEncoding,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_opt_String(forcedEncoding, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_normalized_book,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiParseEpubConstMeta,
        argValues: [bytes, forcedEncoding],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiParseEpubConstMeta => const TaskConstMeta(
    debugName: 'parse_epub',
    argNames: ['bytes', 'forcedEncoding'],
  );

  @override
  Future<NormalizedBook> crateApiApiParseFb2({
    required List<int> bytes,
    String? forcedEncoding,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_opt_String(forcedEncoding, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_normalized_book,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiParseFb2ConstMeta,
        argValues: [bytes, forcedEncoding],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiParseFb2ConstMeta => const TaskConstMeta(
    debugName: 'parse_fb2',
    argNames: ['bytes', 'forcedEncoding'],
  );

  @override
  Future<List<ReaderBlock>> crateApiApiParseHtmlBlocks({required String html}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(html, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_reader_block,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiParseHtmlBlocksConstMeta,
        argValues: [html],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiParseHtmlBlocksConstMeta => const TaskConstMeta(
    debugName: 'parse_html_blocks',
    argNames: ['html'],
  );

  @override
  Future<NormalizedBook> crateApiApiParseMobi({
    required List<int> bytes,
    String? forcedEncoding,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_opt_String(forcedEncoding, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_normalized_book,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiParseMobiConstMeta,
        argValues: [bytes, forcedEncoding],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiParseMobiConstMeta => const TaskConstMeta(
    debugName: 'parse_mobi',
    argNames: ['bytes', 'forcedEncoding'],
  );

  @override
  Future<NormalizedBook> crateApiApiParseRtf({
    required List<int> bytes,
    String? forcedEncoding,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_opt_String(forcedEncoding, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_normalized_book,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiParseRtfConstMeta,
        argValues: [bytes, forcedEncoding],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiParseRtfConstMeta => const TaskConstMeta(
    debugName: 'parse_rtf',
    argNames: ['bytes', 'forcedEncoding'],
  );

  @override
  Future<List<TocEntry>> crateApiApiParseToc({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_toc_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiParseTocConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiParseTocConstMeta => const TaskConstMeta(
    debugName: 'parse_toc',
    argNames: ['path'],
  );

  @override
  Future<NormalizedBook> crateApiApiParseTxt({
    required List<int> bytes,
    String? forcedEncoding,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_opt_String(forcedEncoding, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_normalized_book,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiParseTxtConstMeta,
        argValues: [bytes, forcedEncoding],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiParseTxtConstMeta => const TaskConstMeta(
    debugName: 'parse_txt',
    argNames: ['bytes', 'forcedEncoding'],
  );

  @override
  Future<Uint8List> crateApiApiRenderPdfThumbnail({
    required String path,
    required int pageIndex,
    required int width,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_u_16(pageIndex, serializer);
          sse_encode_u_16(width, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiRenderPdfThumbnailConstMeta,
        argValues: [path, pageIndex, width],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiRenderPdfThumbnailConstMeta => const TaskConstMeta(
    debugName: 'render_pdf_thumbnail',
    argNames: ['path', 'pageIndex', 'width'],
  );

  @override
  Future<NormalizedBook> crateApiApiSafeParseBook({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_normalized_book,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiSafeParseBookConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiSafeParseBookConstMeta => const TaskConstMeta(
    debugName: 'safe_parse_book',
    argNames: ['path'],
  );

  @override
  Future<String> crateApiApiSha256Hash({
    required List<int> bytes,
    BigInt? maxBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_opt_box_autoadd_usize(maxBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiSha256HashConstMeta,
        argValues: [bytes, maxBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiSha256HashConstMeta => const TaskConstMeta(
    debugName: 'sha256_hash',
    argNames: ['bytes', 'maxBytes'],
  );

  @override
  Future<BookValidationResult> crateApiApiValidateBook({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_book_validation_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiValidateBookConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiValidateBookConstMeta => const TaskConstMeta(
    debugName: 'validate_book',
    argNames: ['path'],
  );

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Value => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Value => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  Value dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ValueImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Value dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ValueImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BlockType dco_decode_block_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BlockType.values[raw as int];
  }

  @protected
  BookAssetMeta dco_decode_book_asset_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BookAssetMeta(
      assetId: dco_decode_String(arr[0]),
      mediaType: dco_decode_String(arr[1]),
      size: dco_decode_usize(arr[2]),
    );
  }

  @protected
  BookFormat dco_decode_book_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BookFormat.values[raw as int];
  }

  @protected
  BookMeta dco_decode_book_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7) throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return BookMeta(
      title: dco_decode_String(arr[0]),
      authors: dco_decode_list_String(arr[1]),
      description: dco_decode_opt_String(arr[2]),
      language: dco_decode_opt_String(arr[3]),
      genres: dco_decode_list_String(arr[4]),
      coverData: dco_decode_opt_list_prim_u_8_strict(arr[5]),
      toc: dco_decode_list_toc_entry(arr[6]),
    );
  }

  @protected
  BookValidationResult dco_decode_book_validation_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BookValidationResult(
      valid: dco_decode_bool(arr[0]),
      emptyChapters: dco_decode_list_prim_i_32_strict(arr[1]),
      duplicateChapters: dco_decode_list_prim_i_32_strict(arr[2]),
      spineTocMismatch: dco_decode_bool(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Value
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
      raw,
    );
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  NormalizedBook dco_decode_box_autoadd_normalized_book(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_normalized_book(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_usize(raw);
  }

  @protected
  ChapterLanguage dco_decode_chapter_language(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ChapterLanguage(
      lang: dco_decode_String(arr[0]),
      confidence: dco_decode_f_64(arr[1]),
    );
  }

  @protected
  EmbeddedImage dco_decode_embedded_image(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return EmbeddedImage(
      id: dco_decode_String(arr[0]),
      mediaType: dco_decode_String(arr[1]),
      data: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FormatCapabilities dco_decode_format_capabilities(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7) throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return FormatCapabilities(
      metadata: dco_decode_bool(arr[0]),
      cover: dco_decode_bool(arr[1]),
      toc: dco_decode_bool(arr[2]),
      text: dco_decode_bool(arr[3]),
      images: dco_decode_bool(arr[4]),
      css: dco_decode_bool(arr[5]),
      footnotes: dco_decode_bool(arr[6]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ImportReport dco_decode_import_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9) throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ImportReport(
      format: dco_decode_book_format(arr[0]),
      parserUsed: dco_decode_String(arr[1]),
      chaptersCount: dco_decode_usize(arr[2]),
      blocksCount: dco_decode_usize(arr[3]),
      imagesCount: dco_decode_usize(arr[4]),
      footnotesCount: dco_decode_usize(arr[5]),
      warnings: dco_decode_list_parse_warning(arr[6]),
      parseTimeMs: dco_decode_u_64(arr[7]),
      fileHash: dco_decode_String(arr[8]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<BookAssetMeta> dco_decode_list_book_asset_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_book_asset_meta).toList();
  }

  @protected
  List<EmbeddedImage> dco_decode_list_embedded_image(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_embedded_image).toList();
  }

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_String).toList();
  }

  @protected
  List<ParseWarning> dco_decode_list_parse_warning(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_parse_warning).toList();
  }

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Int32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ReaderBlock> dco_decode_list_reader_block(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_reader_block).toList();
  }

  @protected
  List<ReaderChapter> dco_decode_list_reader_chapter(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_reader_chapter).toList();
  }

  @protected
  List<RichSpan> dco_decode_list_rich_span(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rich_span).toList();
  }

  @protected
  List<TocEntry> dco_decode_list_toc_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_toc_entry).toList();
  }

  @protected
  NormalizedBook dco_decode_normalized_book(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12) throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return NormalizedBook(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      authors: dco_decode_list_String(arr[2]),
      description: dco_decode_opt_String(arr[3]),
      coverUrl: dco_decode_opt_String(arr[4]),
      chapters: dco_decode_list_reader_chapter(arr[5]),
      metadata:
          dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
            arr[6],
          ),
      bookFormat: dco_decode_book_format(arr[7]),
      language: dco_decode_opt_String(arr[8]),
      warnings: dco_decode_list_parse_warning(arr[9]),
      images: dco_decode_list_embedded_image(arr[10]),
      toc: dco_decode_list_toc_entry(arr[11]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  Value?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
            raw,
          );
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_usize(raw);
  }

  @protected
  List<List<String>>? dco_decode_opt_list_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_list_String(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  List<ReaderBlock>? dco_decode_opt_list_reader_block(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_reader_block(raw);
  }

  @protected
  List<RichSpan>? dco_decode_opt_list_rich_span(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_rich_span(raw);
  }

  @protected
  ParseWarning dco_decode_parse_warning(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1) throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return ParseWarning(
      message: dco_decode_String(arr[0]),
    );
  }

  @protected
  ReaderBlock dco_decode_reader_block(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14) throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return ReaderBlock(
      index: dco_decode_i_32(arr[0]),
      text: dco_decode_String(arr[1]),
      blockType: dco_decode_block_type(arr[2]),
      imageUrl: dco_decode_opt_String(arr[3]),
      noteRef: dco_decode_opt_String(arr[4]),
      richSpans: dco_decode_opt_list_rich_span(arr[5]),
      headingLevel: dco_decode_opt_box_autoadd_i_32(arr[6]),
      ordered: dco_decode_opt_box_autoadd_bool(arr[7]),
      listItems: dco_decode_opt_list_reader_block(arr[8]),
      tableRows: dco_decode_opt_list_list_String(arr[9]),
      imageAlt: dco_decode_opt_String(arr[10]),
      textIndent: dco_decode_opt_box_autoadd_f_64(arr[11]),
      textAlign: dco_decode_opt_String(arr[12]),
      noteId: dco_decode_opt_String(arr[13]),
    );
  }

  @protected
  ReaderChapter dco_decode_reader_chapter(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ReaderChapter(
      index: dco_decode_i_32(arr[0]),
      title: dco_decode_String(arr[1]),
      blocks: dco_decode_list_reader_block(arr[2]),
    );
  }

  @protected
  RichSpan dco_decode_rich_span(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6) throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return RichSpan(
      text: dco_decode_String(arr[0]),
      bold: dco_decode_bool(arr[1]),
      italic: dco_decode_bool(arr[2]),
      superscript: dco_decode_bool(arr[3]),
      href: dco_decode_opt_String(arr[4]),
      lineBreak: dco_decode_bool(arr[5]),
    );
  }

  @protected
  TocEntry dco_decode_toc_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TocEntry(
      title: dco_decode_String(arr[0]),
      chapterIndex: dco_decode_i_32(arr[1]),
      children: dco_decode_list_toc_entry(arr[2]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  Value sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ValueImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Value sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ValueImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BlockType sse_decode_block_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_i_32(deserializer);
    return BlockType.values[inner];
  }

  @protected
  BookAssetMeta sse_decode_book_asset_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_assetId = sse_decode_String(deserializer);
    final var_mediaType = sse_decode_String(deserializer);
    final var_size = sse_decode_usize(deserializer);
    return BookAssetMeta(
      assetId: var_assetId,
      mediaType: var_mediaType,
      size: var_size,
    );
  }

  @protected
  BookFormat sse_decode_book_format(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_i_32(deserializer);
    return BookFormat.values[inner];
  }

  @protected
  BookMeta sse_decode_book_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_title = sse_decode_String(deserializer);
    final var_authors = sse_decode_list_String(deserializer);
    final var_description = sse_decode_opt_String(deserializer);
    final var_language = sse_decode_opt_String(deserializer);
    final var_genres = sse_decode_list_String(deserializer);
    final var_coverData = sse_decode_opt_list_prim_u_8_strict(deserializer);
    final var_toc = sse_decode_list_toc_entry(deserializer);
    return BookMeta(
      title: var_title,
      authors: var_authors,
      description: var_description,
      language: var_language,
      genres: var_genres,
      coverData: var_coverData,
      toc: var_toc,
    );
  }

  @protected
  BookValidationResult sse_decode_book_validation_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_valid = sse_decode_bool(deserializer);
    final var_emptyChapters = sse_decode_list_prim_i_32_strict(deserializer);
    final var_duplicateChapters = sse_decode_list_prim_i_32_strict(
      deserializer,
    );
    final var_spineTocMismatch = sse_decode_bool(deserializer);
    return BookValidationResult(
      valid: var_valid,
      emptyChapters: var_emptyChapters,
      duplicateChapters: var_duplicateChapters,
      spineTocMismatch: var_spineTocMismatch,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Value
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
      deserializer,
    ));
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  NormalizedBook sse_decode_box_autoadd_normalized_book(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_normalized_book(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_usize(deserializer));
  }

  @protected
  ChapterLanguage sse_decode_chapter_language(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_lang = sse_decode_String(deserializer);
    final var_confidence = sse_decode_f_64(deserializer);
    return ChapterLanguage(lang: var_lang, confidence: var_confidence);
  }

  @protected
  EmbeddedImage sse_decode_embedded_image(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_id = sse_decode_String(deserializer);
    final var_mediaType = sse_decode_String(deserializer);
    final var_data = sse_decode_list_prim_u_8_strict(deserializer);
    return EmbeddedImage(id: var_id, mediaType: var_mediaType, data: var_data);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FormatCapabilities sse_decode_format_capabilities(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_metadata = sse_decode_bool(deserializer);
    final var_cover = sse_decode_bool(deserializer);
    final var_toc = sse_decode_bool(deserializer);
    final var_text = sse_decode_bool(deserializer);
    final var_images = sse_decode_bool(deserializer);
    final var_css = sse_decode_bool(deserializer);
    final var_footnotes = sse_decode_bool(deserializer);
    return FormatCapabilities(
      metadata: var_metadata,
      cover: var_cover,
      toc: var_toc,
      text: var_text,
      images: var_images,
      css: var_css,
      footnotes: var_footnotes,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  ImportReport sse_decode_import_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_format = sse_decode_book_format(deserializer);
    final var_parserUsed = sse_decode_String(deserializer);
    final var_chaptersCount = sse_decode_usize(deserializer);
    final var_blocksCount = sse_decode_usize(deserializer);
    final var_imagesCount = sse_decode_usize(deserializer);
    final var_footnotesCount = sse_decode_usize(deserializer);
    final var_warnings = sse_decode_list_parse_warning(deserializer);
    final var_parseTimeMs = sse_decode_u_64(deserializer);
    final var_fileHash = sse_decode_String(deserializer);
    return ImportReport(
      format: var_format,
      parserUsed: var_parserUsed,
      chaptersCount: var_chaptersCount,
      blocksCount: var_blocksCount,
      imagesCount: var_imagesCount,
      footnotesCount: var_footnotesCount,
      warnings: var_warnings,
      parseTimeMs: var_parseTimeMs,
      fileHash: var_fileHash,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<BookAssetMeta> sse_decode_list_book_asset_meta(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <BookAssetMeta>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_book_asset_meta(deserializer));
    }
    return ans_;
  }

  @protected
  List<EmbeddedImage> sse_decode_list_embedded_image(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <EmbeddedImage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_embedded_image(deserializer));
    }
    return ans_;
  }

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <List<String>>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ParseWarning> sse_decode_list_parse_warning(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <ParseWarning>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_parse_warning(deserializer));
    }
    return ans_;
  }

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ReaderBlock> sse_decode_list_reader_block(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <ReaderBlock>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_reader_block(deserializer));
    }
    return ans_;
  }

  @protected
  List<ReaderChapter> sse_decode_list_reader_chapter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <ReaderChapter>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_reader_chapter(deserializer));
    }
    return ans_;
  }

  @protected
  List<RichSpan> sse_decode_list_rich_span(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <RichSpan>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rich_span(deserializer));
    }
    return ans_;
  }

  @protected
  List<TocEntry> sse_decode_list_toc_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <TocEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_toc_entry(deserializer));
    }
    return ans_;
  }

  @protected
  NormalizedBook sse_decode_normalized_book(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_id = sse_decode_String(deserializer);
    final var_title = sse_decode_String(deserializer);
    final var_authors = sse_decode_list_String(deserializer);
    final var_description = sse_decode_opt_String(deserializer);
    final var_coverUrl = sse_decode_opt_String(deserializer);
    final var_chapters = sse_decode_list_reader_chapter(deserializer);
    final var_metadata =
        sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          deserializer,
        );
    final var_bookFormat = sse_decode_book_format(deserializer);
    final var_language = sse_decode_opt_String(deserializer);
    final var_warnings = sse_decode_list_parse_warning(deserializer);
    final var_images = sse_decode_list_embedded_image(deserializer);
    final var_toc = sse_decode_list_toc_entry(deserializer);
    return NormalizedBook(
      id: var_id,
      title: var_title,
      authors: var_authors,
      description: var_description,
      coverUrl: var_coverUrl,
      chapters: var_chapters,
      metadata: var_metadata,
      bookFormat: var_bookFormat,
      language: var_language,
      warnings: var_warnings,
      images: var_images,
      toc: var_toc,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Value?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_usize(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<List<String>>? sse_decode_opt_list_list_String(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_list_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<ReaderBlock>? sse_decode_opt_list_reader_block(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_reader_block(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<RichSpan>? sse_decode_opt_list_rich_span(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_rich_span(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ParseWarning sse_decode_parse_warning(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_message = sse_decode_String(deserializer);
    return ParseWarning(message: var_message);
  }

  @protected
  ReaderBlock sse_decode_reader_block(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_index = sse_decode_i_32(deserializer);
    final var_text = sse_decode_String(deserializer);
    final var_blockType = sse_decode_block_type(deserializer);
    final var_imageUrl = sse_decode_opt_String(deserializer);
    final var_noteRef = sse_decode_opt_String(deserializer);
    final var_richSpans = sse_decode_opt_list_rich_span(deserializer);
    final var_headingLevel = sse_decode_opt_box_autoadd_i_32(deserializer);
    final var_ordered = sse_decode_opt_box_autoadd_bool(deserializer);
    final var_listItems = sse_decode_opt_list_reader_block(deserializer);
    final var_tableRows = sse_decode_opt_list_list_String(deserializer);
    final var_imageAlt = sse_decode_opt_String(deserializer);
    final var_textIndent = sse_decode_opt_box_autoadd_f_64(deserializer);
    final var_textAlign = sse_decode_opt_String(deserializer);
    final var_noteId = sse_decode_opt_String(deserializer);
    return ReaderBlock(
      index: var_index,
      text: var_text,
      blockType: var_blockType,
      imageUrl: var_imageUrl,
      noteRef: var_noteRef,
      richSpans: var_richSpans,
      headingLevel: var_headingLevel,
      ordered: var_ordered,
      listItems: var_listItems,
      tableRows: var_tableRows,
      imageAlt: var_imageAlt,
      textIndent: var_textIndent,
      textAlign: var_textAlign,
      noteId: var_noteId,
    );
  }

  @protected
  ReaderChapter sse_decode_reader_chapter(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_index = sse_decode_i_32(deserializer);
    final var_title = sse_decode_String(deserializer);
    final var_blocks = sse_decode_list_reader_block(deserializer);
    return ReaderChapter(
      index: var_index,
      title: var_title,
      blocks: var_blocks,
    );
  }

  @protected
  RichSpan sse_decode_rich_span(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_text = sse_decode_String(deserializer);
    final var_bold = sse_decode_bool(deserializer);
    final var_italic = sse_decode_bool(deserializer);
    final var_superscript = sse_decode_bool(deserializer);
    final var_href = sse_decode_opt_String(deserializer);
    final var_lineBreak = sse_decode_bool(deserializer);
    return RichSpan(
      text: var_text,
      bold: var_bold,
      italic: var_italic,
      superscript: var_superscript,
      href: var_href,
      lineBreak: var_lineBreak,
    );
  }

  @protected
  TocEntry sse_decode_toc_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_title = sse_decode_String(deserializer);
    final var_chapterIndex = sse_decode_i_32(deserializer);
    final var_children = sse_decode_list_toc_entry(deserializer);
    return TocEntry(
      title: var_title,
      chapterIndex: var_chapterIndex,
      children: var_children,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    Value self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ValueImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    Value self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize((self as ValueImpl).frbInternalSseEncode(), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_block_type(BlockType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_book_asset_meta(
    BookAssetMeta self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.assetId, serializer);
    sse_encode_String(self.mediaType, serializer);
    sse_encode_usize(self.size, serializer);
  }

  @protected
  void sse_encode_book_format(BookFormat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_book_meta(BookMeta self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_list_String(self.authors, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_opt_String(self.language, serializer);
    sse_encode_list_String(self.genres, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.coverData, serializer);
    sse_encode_list_toc_entry(self.toc, serializer);
  }

  @protected
  void sse_encode_book_validation_result(
    BookValidationResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.valid, serializer);
    sse_encode_list_prim_i_32_strict(self.emptyChapters, serializer);
    sse_encode_list_prim_i_32_strict(self.duplicateChapters, serializer);
    sse_encode_bool(self.spineTocMismatch, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    Value self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
      self,
      serializer,
    );
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_normalized_book(
    NormalizedBook self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_normalized_book(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self, serializer);
  }

  @protected
  void sse_encode_chapter_language(
    ChapterLanguage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.lang, serializer);
    sse_encode_f_64(self.confidence, serializer);
  }

  @protected
  void sse_encode_embedded_image(EmbeddedImage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.mediaType, serializer);
    sse_encode_list_prim_u_8_strict(self.data, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_format_capabilities(
    FormatCapabilities self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.metadata, serializer);
    sse_encode_bool(self.cover, serializer);
    sse_encode_bool(self.toc, serializer);
    sse_encode_bool(self.text, serializer);
    sse_encode_bool(self.images, serializer);
    sse_encode_bool(self.css, serializer);
    sse_encode_bool(self.footnotes, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_import_report(ImportReport self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_book_format(self.format, serializer);
    sse_encode_String(self.parserUsed, serializer);
    sse_encode_usize(self.chaptersCount, serializer);
    sse_encode_usize(self.blocksCount, serializer);
    sse_encode_usize(self.imagesCount, serializer);
    sse_encode_usize(self.footnotesCount, serializer);
    sse_encode_list_parse_warning(self.warnings, serializer);
    sse_encode_u_64(self.parseTimeMs, serializer);
    sse_encode_String(self.fileHash, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_book_asset_meta(
    List<BookAssetMeta> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_book_asset_meta(item, serializer);
    }
  }

  @protected
  void sse_encode_list_embedded_image(
    List<EmbeddedImage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_embedded_image(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_String(
    List<List<String>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_parse_warning(
    List<ParseWarning> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_parse_warning(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_reader_block(
    List<ReaderBlock> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_reader_block(item, serializer);
    }
  }

  @protected
  void sse_encode_list_reader_chapter(
    List<ReaderChapter> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_reader_chapter(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rich_span(
    List<RichSpan> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rich_span(item, serializer);
    }
  }

  @protected
  void sse_encode_list_toc_entry(
    List<TocEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_toc_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_normalized_book(
    NormalizedBook self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_list_String(self.authors, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_opt_String(self.coverUrl, serializer);
    sse_encode_list_reader_chapter(self.chapters, serializer);
    sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
      self.metadata,
      serializer,
    );
    sse_encode_book_format(self.bookFormat, serializer);
    sse_encode_opt_String(self.language, serializer);
    sse_encode_list_parse_warning(self.warnings, serializer);
    sse_encode_list_embedded_image(self.images, serializer);
    sse_encode_list_toc_entry(self.toc, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    Value? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
        self,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_usize(
    BigInt? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_usize(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_list_String(
    List<List<String>>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_list_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_reader_block(
    List<ReaderBlock>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_reader_block(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_rich_span(
    List<RichSpan>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_rich_span(self, serializer);
    }
  }

  @protected
  void sse_encode_parse_warning(ParseWarning self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_reader_block(ReaderBlock self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_block_type(self.blockType, serializer);
    sse_encode_opt_String(self.imageUrl, serializer);
    sse_encode_opt_String(self.noteRef, serializer);
    sse_encode_opt_list_rich_span(self.richSpans, serializer);
    sse_encode_opt_box_autoadd_i_32(self.headingLevel, serializer);
    sse_encode_opt_box_autoadd_bool(self.ordered, serializer);
    sse_encode_opt_list_reader_block(self.listItems, serializer);
    sse_encode_opt_list_list_String(self.tableRows, serializer);
    sse_encode_opt_String(self.imageAlt, serializer);
    sse_encode_opt_box_autoadd_f_64(self.textIndent, serializer);
    sse_encode_opt_String(self.textAlign, serializer);
    sse_encode_opt_String(self.noteId, serializer);
  }

  @protected
  void sse_encode_reader_chapter(ReaderChapter self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_list_reader_block(self.blocks, serializer);
  }

  @protected
  void sse_encode_rich_span(RichSpan self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_bool(self.bold, serializer);
    sse_encode_bool(self.italic, serializer);
    sse_encode_bool(self.superscript, serializer);
    sse_encode_opt_String(self.href, serializer);
    sse_encode_bool(self.lineBreak, serializer);
  }

  @protected
  void sse_encode_toc_entry(TocEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_i_32(self.chapterIndex, serializer);
    sse_encode_list_toc_entry(self.children, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class ValueImpl extends RustOpaque implements Value {
  // Not to be used by end users
  ValueImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ValueImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib.instance.api.rust_arc_increment_strong_count_Value,
    rustArcDecrementStrongCount: RustLib.instance.api.rust_arc_decrement_strong_count_Value,
    rustArcDecrementStrongCountPtr: RustLib.instance.api.rust_arc_decrement_strong_count_ValuePtr,
  );
}
