// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'api/api.dart';
import 'api/models.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1686640177;

  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
    stem: 'glibusta_core',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiModelsBlockTypeAsStr({required BlockType that});

  Future<BlockType> crateApiModelsBlockTypeFromStr({required String s});

  Future<List<String>> crateApiApiDecodeZipEntries({required List<int> bytes});

  Future<String> crateApiApiDetectEncoding({required List<int> bytes});

  Future<Uint8List> crateApiApiExtractCover({
    required List<int> bytes,
    required String format,
    String? forcedEncoding,
  });

  Future<BookMeta> crateApiApiExtractMetadata({
    required List<int> bytes,
    required String format,
    String? forcedEncoding,
  });

  Future<Uint8List> crateApiApiExtractZipEntry({
    required List<int> bytes,
    required String entryName,
  });

  Future<NormalizedBook> crateApiModelsNormalizedBookFromJsonStr({
    required String json,
  });

  Future<String> crateApiModelsNormalizedBookToJsonString({
    required NormalizedBook that,
  });

  Future<NormalizedBook> crateApiApiParseBook({
    required List<int> bytes,
    required String format,
    String? forcedEncoding,
  });

  Future<NormalizedBook> crateApiApiParseDocx({
    required List<int> bytes,
    String? forcedEncoding,
  });

  Future<NormalizedBook> crateApiApiParseEpub({
    required List<int> bytes,
    String? forcedEncoding,
  });

  Future<NormalizedBook> crateApiApiParseFb2({
    required List<int> bytes,
    String? forcedEncoding,
  });

  Future<List<ReaderBlock>> crateApiApiParseHtmlBlocks({required String html});

  Future<NormalizedBook> crateApiApiParseMobi({
    required List<int> bytes,
    String? forcedEncoding,
  });

  Future<NormalizedBook> crateApiApiParseRtf({
    required List<int> bytes,
    String? forcedEncoding,
  });

  Future<NormalizedBook> crateApiApiParseTxt({
    required List<int> bytes,
    String? forcedEncoding,
  });

  Future<Uint8List> crateApiApiRenderPdfThumbnail({
    required String path,
    required int pageIndex,
    required int width,
  });

  Future<String> crateApiApiSha256Hash({
    required List<int> bytes,
    BigInt? maxBytes,
  });

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Value;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Value;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ValuePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiModelsBlockTypeAsStr({required BlockType that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_block_type(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelsBlockTypeAsStrConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsBlockTypeAsStrConstMeta => const TaskConstMeta(
    debugName: 'block_type_as_str',
    argNames: ['that'],
  );

  @override
  Future<BlockType> crateApiModelsBlockTypeFromStr({required String s}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(s, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_block_type,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelsBlockTypeFromStrConstMeta,
        argValues: [s],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsBlockTypeFromStrConstMeta => const TaskConstMeta(
    debugName: 'block_type_from_str',
    argNames: ['s'],
  );

  @override
  Future<List<String>> crateApiApiDecodeZipEntries({required List<int> bytes}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiDecodeZipEntriesConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiDecodeZipEntriesConstMeta => const TaskConstMeta(
    debugName: 'decode_zip_entries',
    argNames: ['bytes'],
  );

  @override
  Future<String> crateApiApiDetectEncoding({required List<int> bytes}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiDetectEncodingConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiDetectEncodingConstMeta => const TaskConstMeta(
    debugName: 'detect_encoding',
    argNames: ['bytes'],
  );

  @override
  Future<Uint8List> crateApiApiExtractCover({
    required List<int> bytes,
    required String format,
    String? forcedEncoding,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_String(format, serializer);
          sse_encode_opt_String(forcedEncoding, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiExtractCoverConstMeta,
        argValues: [bytes, format, forcedEncoding],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiExtractCoverConstMeta => const TaskConstMeta(
    debugName: 'extract_cover',
    argNames: ['bytes', 'format', 'forcedEncoding'],
  );

  @override
  Future<BookMeta> crateApiApiExtractMetadata({
    required List<int> bytes,
    required String format,
    String? forcedEncoding,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_String(format, serializer);
          sse_encode_opt_String(forcedEncoding, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_book_meta,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiExtractMetadataConstMeta,
        argValues: [bytes, format, forcedEncoding],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiExtractMetadataConstMeta => const TaskConstMeta(
    debugName: 'extract_metadata',
    argNames: ['bytes', 'format', 'forcedEncoding'],
  );

  @override
  Future<Uint8List> crateApiApiExtractZipEntry({
    required List<int> bytes,
    required String entryName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_String(entryName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiExtractZipEntryConstMeta,
        argValues: [bytes, entryName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiExtractZipEntryConstMeta => const TaskConstMeta(
    debugName: 'extract_zip_entry',
    argNames: ['bytes', 'entryName'],
  );

  @override
  Future<NormalizedBook> crateApiModelsNormalizedBookFromJsonStr({
    required String json,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_normalized_book,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModelsNormalizedBookFromJsonStrConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsNormalizedBookFromJsonStrConstMeta => const TaskConstMeta(
    debugName: 'normalized_book_from_json_str',
    argNames: ['json'],
  );

  @override
  Future<String> crateApiModelsNormalizedBookToJsonString({
    required NormalizedBook that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_normalized_book(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModelsNormalizedBookToJsonStringConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsNormalizedBookToJsonStringConstMeta => const TaskConstMeta(
    debugName: 'normalized_book_to_json_string',
    argNames: ['that'],
  );

  @override
  Future<NormalizedBook> crateApiApiParseBook({
    required List<int> bytes,
    required String format,
    String? forcedEncoding,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_String(format, serializer);
          sse_encode_opt_String(forcedEncoding, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_normalized_book,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiParseBookConstMeta,
        argValues: [bytes, format, forcedEncoding],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiParseBookConstMeta => const TaskConstMeta(
    debugName: 'parse_book',
    argNames: ['bytes', 'format', 'forcedEncoding'],
  );

  @override
  Future<NormalizedBook> crateApiApiParseDocx({
    required List<int> bytes,
    String? forcedEncoding,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_opt_String(forcedEncoding, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_normalized_book,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiParseDocxConstMeta,
        argValues: [bytes, forcedEncoding],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiParseDocxConstMeta => const TaskConstMeta(
    debugName: 'parse_docx',
    argNames: ['bytes', 'forcedEncoding'],
  );

  @override
  Future<NormalizedBook> crateApiApiParseEpub({
    required List<int> bytes,
    String? forcedEncoding,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_opt_String(forcedEncoding, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_normalized_book,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiParseEpubConstMeta,
        argValues: [bytes, forcedEncoding],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiParseEpubConstMeta => const TaskConstMeta(
    debugName: 'parse_epub',
    argNames: ['bytes', 'forcedEncoding'],
  );

  @override
  Future<NormalizedBook> crateApiApiParseFb2({
    required List<int> bytes,
    String? forcedEncoding,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_opt_String(forcedEncoding, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_normalized_book,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiParseFb2ConstMeta,
        argValues: [bytes, forcedEncoding],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiParseFb2ConstMeta => const TaskConstMeta(
    debugName: 'parse_fb2',
    argNames: ['bytes', 'forcedEncoding'],
  );

  @override
  Future<List<ReaderBlock>> crateApiApiParseHtmlBlocks({required String html}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(html, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_reader_block,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiParseHtmlBlocksConstMeta,
        argValues: [html],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiParseHtmlBlocksConstMeta => const TaskConstMeta(
    debugName: 'parse_html_blocks',
    argNames: ['html'],
  );

  @override
  Future<NormalizedBook> crateApiApiParseMobi({
    required List<int> bytes,
    String? forcedEncoding,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_opt_String(forcedEncoding, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_normalized_book,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiParseMobiConstMeta,
        argValues: [bytes, forcedEncoding],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiParseMobiConstMeta => const TaskConstMeta(
    debugName: 'parse_mobi',
    argNames: ['bytes', 'forcedEncoding'],
  );

  @override
  Future<NormalizedBook> crateApiApiParseRtf({
    required List<int> bytes,
    String? forcedEncoding,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_opt_String(forcedEncoding, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_normalized_book,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiParseRtfConstMeta,
        argValues: [bytes, forcedEncoding],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiParseRtfConstMeta => const TaskConstMeta(
    debugName: 'parse_rtf',
    argNames: ['bytes', 'forcedEncoding'],
  );

  @override
  Future<NormalizedBook> crateApiApiParseTxt({
    required List<int> bytes,
    String? forcedEncoding,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_opt_String(forcedEncoding, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_normalized_book,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiParseTxtConstMeta,
        argValues: [bytes, forcedEncoding],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiParseTxtConstMeta => const TaskConstMeta(
    debugName: 'parse_txt',
    argNames: ['bytes', 'forcedEncoding'],
  );

  @override
  Future<Uint8List> crateApiApiRenderPdfThumbnail({
    required String path,
    required int pageIndex,
    required int width,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_u_16(pageIndex, serializer);
          sse_encode_u_16(width, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiRenderPdfThumbnailConstMeta,
        argValues: [path, pageIndex, width],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiRenderPdfThumbnailConstMeta => const TaskConstMeta(
    debugName: 'render_pdf_thumbnail',
    argNames: ['path', 'pageIndex', 'width'],
  );

  @override
  Future<String> crateApiApiSha256Hash({
    required List<int> bytes,
    BigInt? maxBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_opt_box_autoadd_usize(maxBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiApiSha256HashConstMeta,
        argValues: [bytes, maxBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiSha256HashConstMeta => const TaskConstMeta(
    debugName: 'sha256_hash',
    argNames: ['bytes', 'maxBytes'],
  );

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Value => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Value => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  Value dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ValueImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Value dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ValueImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BlockType dco_decode_block_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BlockType.values[raw as int];
  }

  @protected
  BookMeta dco_decode_book_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BookMeta(
      title: dco_decode_String(arr[0]),
      authors: dco_decode_list_String(arr[1]),
      description: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Value
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
      raw,
    );
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  NormalizedBook dco_decode_box_autoadd_normalized_book(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_normalized_book(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_usize(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ReaderBlock> dco_decode_list_reader_block(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_reader_block).toList();
  }

  @protected
  List<ReaderChapter> dco_decode_list_reader_chapter(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_reader_chapter).toList();
  }

  @protected
  List<RichSpan> dco_decode_list_rich_span(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rich_span).toList();
  }

  @protected
  NormalizedBook dco_decode_normalized_book(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7) throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return NormalizedBook(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      authors: dco_decode_list_String(arr[2]),
      description: dco_decode_opt_String(arr[3]),
      coverUrl: dco_decode_opt_String(arr[4]),
      chapters: dco_decode_list_reader_chapter(arr[5]),
      metadata:
          dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
            arr[6],
          ),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  Value?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
            raw,
          );
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_usize(raw);
  }

  @protected
  List<List<String>>? dco_decode_opt_list_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_list_String(raw);
  }

  @protected
  List<ReaderBlock>? dco_decode_opt_list_reader_block(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_reader_block(raw);
  }

  @protected
  List<RichSpan>? dco_decode_opt_list_rich_span(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_rich_span(raw);
  }

  @protected
  ReaderBlock dco_decode_reader_block(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14) throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return ReaderBlock(
      index: dco_decode_i_32(arr[0]),
      text: dco_decode_String(arr[1]),
      blockType: dco_decode_block_type(arr[2]),
      imageUrl: dco_decode_opt_String(arr[3]),
      noteRef: dco_decode_opt_String(arr[4]),
      richSpans: dco_decode_opt_list_rich_span(arr[5]),
      headingLevel: dco_decode_opt_box_autoadd_i_32(arr[6]),
      ordered: dco_decode_opt_box_autoadd_bool(arr[7]),
      listItems: dco_decode_opt_list_reader_block(arr[8]),
      tableRows: dco_decode_opt_list_list_String(arr[9]),
      imageAlt: dco_decode_opt_String(arr[10]),
      textIndent: dco_decode_opt_box_autoadd_f_64(arr[11]),
      textAlign: dco_decode_opt_String(arr[12]),
      noteId: dco_decode_opt_String(arr[13]),
    );
  }

  @protected
  ReaderChapter dco_decode_reader_chapter(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ReaderChapter(
      index: dco_decode_i_32(arr[0]),
      title: dco_decode_String(arr[1]),
      blocks: dco_decode_list_reader_block(arr[2]),
    );
  }

  @protected
  RichSpan dco_decode_rich_span(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6) throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return RichSpan(
      text: dco_decode_String(arr[0]),
      bold: dco_decode_bool(arr[1]),
      italic: dco_decode_bool(arr[2]),
      superscript: dco_decode_bool(arr[3]),
      href: dco_decode_opt_String(arr[4]),
      lineBreak: dco_decode_bool(arr[5]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  Value sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ValueImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Value sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ValueImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BlockType sse_decode_block_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_i_32(deserializer);
    return BlockType.values[inner];
  }

  @protected
  BookMeta sse_decode_book_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_title = sse_decode_String(deserializer);
    final var_authors = sse_decode_list_String(deserializer);
    final var_description = sse_decode_opt_String(deserializer);
    return BookMeta(
      title: var_title,
      authors: var_authors,
      description: var_description,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Value
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
      deserializer,
    ));
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  NormalizedBook sse_decode_box_autoadd_normalized_book(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_normalized_book(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_usize(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <List<String>>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ReaderBlock> sse_decode_list_reader_block(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <ReaderBlock>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_reader_block(deserializer));
    }
    return ans_;
  }

  @protected
  List<ReaderChapter> sse_decode_list_reader_chapter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <ReaderChapter>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_reader_chapter(deserializer));
    }
    return ans_;
  }

  @protected
  List<RichSpan> sse_decode_list_rich_span(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <RichSpan>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rich_span(deserializer));
    }
    return ans_;
  }

  @protected
  NormalizedBook sse_decode_normalized_book(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_id = sse_decode_String(deserializer);
    final var_title = sse_decode_String(deserializer);
    final var_authors = sse_decode_list_String(deserializer);
    final var_description = sse_decode_opt_String(deserializer);
    final var_coverUrl = sse_decode_opt_String(deserializer);
    final var_chapters = sse_decode_list_reader_chapter(deserializer);
    final var_metadata =
        sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
          deserializer,
        );
    return NormalizedBook(
      id: var_id,
      title: var_title,
      authors: var_authors,
      description: var_description,
      coverUrl: var_coverUrl,
      chapters: var_chapters,
      metadata: var_metadata,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Value?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_usize(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<List<String>>? sse_decode_opt_list_list_String(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_list_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<ReaderBlock>? sse_decode_opt_list_reader_block(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_reader_block(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<RichSpan>? sse_decode_opt_list_rich_span(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_rich_span(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ReaderBlock sse_decode_reader_block(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_index = sse_decode_i_32(deserializer);
    final var_text = sse_decode_String(deserializer);
    final var_blockType = sse_decode_block_type(deserializer);
    final var_imageUrl = sse_decode_opt_String(deserializer);
    final var_noteRef = sse_decode_opt_String(deserializer);
    final var_richSpans = sse_decode_opt_list_rich_span(deserializer);
    final var_headingLevel = sse_decode_opt_box_autoadd_i_32(deserializer);
    final var_ordered = sse_decode_opt_box_autoadd_bool(deserializer);
    final var_listItems = sse_decode_opt_list_reader_block(deserializer);
    final var_tableRows = sse_decode_opt_list_list_String(deserializer);
    final var_imageAlt = sse_decode_opt_String(deserializer);
    final var_textIndent = sse_decode_opt_box_autoadd_f_64(deserializer);
    final var_textAlign = sse_decode_opt_String(deserializer);
    final var_noteId = sse_decode_opt_String(deserializer);
    return ReaderBlock(
      index: var_index,
      text: var_text,
      blockType: var_blockType,
      imageUrl: var_imageUrl,
      noteRef: var_noteRef,
      richSpans: var_richSpans,
      headingLevel: var_headingLevel,
      ordered: var_ordered,
      listItems: var_listItems,
      tableRows: var_tableRows,
      imageAlt: var_imageAlt,
      textIndent: var_textIndent,
      textAlign: var_textAlign,
      noteId: var_noteId,
    );
  }

  @protected
  ReaderChapter sse_decode_reader_chapter(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_index = sse_decode_i_32(deserializer);
    final var_title = sse_decode_String(deserializer);
    final var_blocks = sse_decode_list_reader_block(deserializer);
    return ReaderChapter(
      index: var_index,
      title: var_title,
      blocks: var_blocks,
    );
  }

  @protected
  RichSpan sse_decode_rich_span(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_text = sse_decode_String(deserializer);
    final var_bold = sse_decode_bool(deserializer);
    final var_italic = sse_decode_bool(deserializer);
    final var_superscript = sse_decode_bool(deserializer);
    final var_href = sse_decode_opt_String(deserializer);
    final var_lineBreak = sse_decode_bool(deserializer);
    return RichSpan(
      text: var_text,
      bold: var_bold,
      italic: var_italic,
      superscript: var_superscript,
      href: var_href,
      lineBreak: var_lineBreak,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    Value self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ValueImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    Value self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize((self as ValueImpl).frbInternalSseEncode(), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_block_type(BlockType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_book_meta(BookMeta self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_list_String(self.authors, serializer);
    sse_encode_opt_String(self.description, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    Value self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
      self,
      serializer,
    );
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_normalized_book(
    NormalizedBook self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_normalized_book(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_String(
    List<List<String>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_reader_block(
    List<ReaderBlock> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_reader_block(item, serializer);
    }
  }

  @protected
  void sse_encode_list_reader_chapter(
    List<ReaderChapter> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_reader_chapter(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rich_span(
    List<RichSpan> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rich_span(item, serializer);
    }
  }

  @protected
  void sse_encode_normalized_book(
    NormalizedBook self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_list_String(self.authors, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_opt_String(self.coverUrl, serializer);
    sse_encode_list_reader_chapter(self.chapters, serializer);
    sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
      self.metadata,
      serializer,
    );
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    Value? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
        self,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_usize(
    BigInt? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_usize(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_list_String(
    List<List<String>>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_list_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_reader_block(
    List<ReaderBlock>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_reader_block(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_rich_span(
    List<RichSpan>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_rich_span(self, serializer);
    }
  }

  @protected
  void sse_encode_reader_block(ReaderBlock self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_block_type(self.blockType, serializer);
    sse_encode_opt_String(self.imageUrl, serializer);
    sse_encode_opt_String(self.noteRef, serializer);
    sse_encode_opt_list_rich_span(self.richSpans, serializer);
    sse_encode_opt_box_autoadd_i_32(self.headingLevel, serializer);
    sse_encode_opt_box_autoadd_bool(self.ordered, serializer);
    sse_encode_opt_list_reader_block(self.listItems, serializer);
    sse_encode_opt_list_list_String(self.tableRows, serializer);
    sse_encode_opt_String(self.imageAlt, serializer);
    sse_encode_opt_box_autoadd_f_64(self.textIndent, serializer);
    sse_encode_opt_String(self.textAlign, serializer);
    sse_encode_opt_String(self.noteId, serializer);
  }

  @protected
  void sse_encode_reader_chapter(ReaderChapter self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_list_reader_block(self.blocks, serializer);
  }

  @protected
  void sse_encode_rich_span(RichSpan self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_bool(self.bold, serializer);
    sse_encode_bool(self.italic, serializer);
    sse_encode_bool(self.superscript, serializer);
    sse_encode_opt_String(self.href, serializer);
    sse_encode_bool(self.lineBreak, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class ValueImpl extends RustOpaque implements Value {
  // Not to be used by end users
  ValueImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ValueImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib.instance.api.rust_arc_increment_strong_count_Value,
    rustArcDecrementStrongCount: RustLib.instance.api.rust_arc_decrement_strong_count_Value,
    rustArcDecrementStrongCountPtr: RustLib.instance.api.rust_arc_decrement_strong_count_ValuePtr,
  );
}
